---
name: Build and Deploy

# Docs
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Inject slug/short variables
        id: inject_vars
        uses: rlespinasse/github-slug-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
